WIP: Make changes in 'files' promises in chroot
cfengine/core pull request #4247
Opened 2020-07-02 09:39 UTC by vpodzime

steps:
- [x] replace `if (DONTDO)` with the new abstraction
- [x] prepare the chroot for making changes in
- [ ] actually make changes in chroot

2020-07-21 14:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cfengine/core?pullRequest=4247) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cfengine/core?pullRequest=4247) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cfengine/core?pullRequest=4247) it.</sub>

2020-07-24 08:30 UTC, vpodzime commented
jenkins: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=5415)](https://ci.cfengine.com/job/pr-pipeline/5415/)

2020-08-20 12:37 UTC, olehermanse approved these changes

2020-08-20 15:18 UTC, olehermanse requested changes

2020-08-20 15:18 UTC, olehermanse commented on cf-agent/verify_files_utils.c
> +                          "set Finder Type code of '%s' to '%s'", file, a->perms.findertype))
Previously all branches of the switch (including default) returned something. But now, it only returns inside the if, no else.

2020-08-20 15:18 UTC, olehermanse commented on cf-agent/verify_files_utils.c
>          }
As mentioned above, this function is missing a return value for some branches.

2020-08-23 18:42 UTC, merged