ENT-6200 Disable flaky test on Solaris 11, also
cfengine/core pull request #4327
Opened 2020-10-01 08:11 UTC by Lex-2008

----

#

2020-10-01 11:06 UTC, olehermanse approved these changes

2020-10-02 12:11 UTC, olehermanse approved these changes

2020-10-05 07:17 UTC, vpodzime requested changes

2020-10-05 07:17 UTC, vpodzime commented on tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
> +      # to be accurate. Also, this test randomly fails on SUSE 11 and 12.
Please do not introduce (more) lies -- Solaris 11 is *not* too slow for timing to be accurate. There are genuine problems in our code or in LMDB.

2020-10-14 08:45 UTC, vpodzime reviewed
Looks good to me otherwise.

2020-10-14 08:45 UTC, vpodzime commented on tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
> +      # this test randomly fails on Soalris and SUSE 11 and 12.
*Soalris*

2020-10-20 09:38 UTC, vpodzime approved these changes
ACK

2020-10-20 10:01 UTC, merged

2020-10-24 12:25 UTC, olehermanse commented
Cherry-picks:
https://github.com/cfengine/core/pull/4360
https://github.com/cfengine/core/pull/4359