ENT-6569 Exclude RHEL5 from diff_mode.cf test
cfengine/core pull request #4426
Opened 2020-12-11 13:19 UTC by Lex-2008

Because it was both failing and causing test.xml file unreadable

2020-12-11 13:27 UTC, Lex-2008 commented
test Jenkins: https://ci.cfengine.com/job/pr-pipeline/5981/

2020-12-11 13:31 UTC, vpodzime approved these changes
ACK

2020-12-11 17:12 UTC, vpodzime submitted a review, later dismissed
ACK

2020-12-12 23:24 UTC, olehermanse commented
@cf-bottom jenkins, please.

2020-12-12 23:28 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=5984)](https://ci.cfengine.com//job/pr-pipeline/5984/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5984/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5984/

2020-12-14 16:19 UTC, Lex-2008 commented
testbuild: https://ci.cfengine.com/job/pr-pipeline/5986/

2020-12-14 18:04 UTC, Lex-2008 commented
green build: https://ci.cfengine.com/job/pr-pipeline/5987/

2020-12-14 22:08 UTC, vpodzime requested changes
Squashing needed.

2020-12-15 10:40 UTC, Lex-2008 commented
Squashed!

2020-12-15 13:38 UTC, olehermanse approved these changes
LGTM

2020-12-16 07:04 UTC, vpodzime approved these changes
ACK

2020-12-16 09:17 UTC, merged