Fixed type-limits compiler warnings
cfengine/core pull request #4657
Opened 2021-05-18 11:13 UTC by KotzaBoss

As `upto` is `size_t` its impossible for it to be less than 0.
At the same time the current algorithm doesnt allow any
underflowing to occur since it uses `ref_str` as an anchor.

The lowest upto can go is 0 if the bracket is found at the start,
at which point all subsequent `memchr` will result in `NULL`.

Ticket: CFE-3418
Changelog: Title

2021-05-18 11:15 UTC, KotzaBoss commented
@cf-bottom jenkins, please

2021-05-18 11:19 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=6579)](https://ci.cfengine.com//job/pr-pipeline/6579/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6579/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6579/

2021-05-18 11:53 UTC, vpodzime submitted a review, later dismissed
ACK. Thanks!

2021-05-18 11:54 UTC, larsewi submitted a review, later dismissed

2021-05-18 12:39 UTC, olehermanse requested changes

2021-05-18 12:39 UTC, olehermanse commented on libpromises/iteration.c
> -        assert(upto >= 0);
This is a compiler warning, not a user facing change. Please remove the changelog entry. (`Changelog: None`).

2021-05-19 12:21 UTC, olehermanse approved these changes

2021-05-19 12:22 UTC, merged