Fixes for custom promise early failures
cfengine/core pull request #4677
Opened 2021-05-26 13:15 UTC by vpodzime

Fixes CFE-3651 and CFE-3645.

2021-05-26 13:51 UTC, vpodzime commented
@cf-bottom jenkins, please

2021-05-26 13:53 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=6624)](https://ci.cfengine.com//job/pr-pipeline/6624/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6624/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6624/

2021-05-27 12:05 UTC, larsewi commented on libpromises/mod_custom.c
> +        /* Details logged in GEtInterpreterAndPath() */
Possible typo `GEtInterpreterAndPath()` should be `GetInterpreterAndPath()` ?

2021-05-27 12:09 UTC, larsewi requested changes
Just one nitpick

2021-05-28 06:28 UTC, larsewi approved these changes
ACK

2021-05-31 14:32 UTC, olehermanse approved these changes
Great!

2021-05-31 14:32 UTC, merged