CFE-3672: Fixed crash when attempting to put methods promises in bundles which are not agent bundles
cfengine/core pull request #4683
Opened 2021-05-28 16:50 UTC by KotzaBoss

Ticket: CFE-3672
Changelog: None

2021-05-28 16:58 UTC, KotzaBoss commented
@cf-bottom jenkins, please

2021-05-28 16:58 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=6643)](https://ci.cfengine.com//job/pr-pipeline/6643/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6643/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6643/

2021-05-29 13:16 UTC, olehermanse requested changes
As discussed in slack, this should have an entry in the changelog. When you put `Changelog: None` it means it won't be included in the changelog.

2021-05-29 13:16 UTC, olehermanse commented on libpromises/policy.c
> +                                 POLICY_ERROR_CONSTRAINT_TYPE_MISMATCH, section->promise_type));
I think this will produce a very confusing error message. Please try it yourself.

2021-05-30 12:32 UTC, KotzaBoss commented
An interesting predicament appeared.
```
bundle common segv
{
  methods:
      "some";
}
```
Raises the [this](https://github.com/cfengine/core/pull/4683/files#diff-9bb2a213157ff70eaff2a9f1cf7a7a7702c0d43cc62f415140801f542d089946R2810) assertion. I believe i tracked down why.
In [these](https://github.com/cfengine/core/pull/4683/files#diff-9bb2a213157ff70eaff2a9f1cf7a7a7702c0d43cc62f415140801f542d089946R2788-R2799) lines is_builtin is true however, the conlist has length 0 therefore it never calls the ConstraintsCheck function to catch the error of having a unsupported.
I pushed a separete commit to address this

2021-05-30 12:33 UTC, KotzaBoss commented
@cf-bottom jenkins, please

2021-05-30 12:39 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=6646)](https://ci.cfengine.com//job/pr-pipeline/6646/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6646/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6646/

2021-05-30 17:48 UTC, olehermanse requested changes

2021-05-30 17:48 UTC, olehermanse commented on libpromises/policy.c
>      for (size_t i = 0; promise_type_syntax->constraints[i].lval != NULL; i++)
By removing the null pointer check, you've introduced a new segfault here.

2021-05-30 17:53 UTC, olehermanse commented
> bundle common segv
> {
>   methods:
>       "some";
> }



> An interesting predicament appeared.
> 
> ```
> bundle common segv
> {
>   methods:
>       "some";
> }
> ```
> 
> Raises the [this](https://github.com/cfengine/core/pull/4683/commits/97e13c4d046ac6236a9e5a07ba59a19cea954198#diff-9bb2a213157ff70eaff2a9f1cf7a7a7702c0d43cc62f415140801f542d089946R2810) assertion. I believe i tracked down why.
> In [these](https://github.com/cfengine/core/blob/master/libpromises/policy.c#L2777-L2787) lines is_builtin is true however, the conlist has length 0 therefore it never calls the ConstraintsCheck function to catch the error of having a unsupported promise type.
> I pushed a separate commit to address this

@KotzaBoss You should add this policy as a test. It can be an errorexit test `.x.cf` or errorlog test `.error.cf`, but it is definitely good to test that it doesn't segfault :)

2021-05-30 17:55 UTC, olehermanse requested changes
The 2 commits don't make much sense to me. It would be much easier to review and understand if you just squashed them into 1 commit. Since in the second one you undo some changes from the first one. Also, the second one says "restructure", but looking at the changes, I see more than just restructuring.

2021-05-31 14:21 UTC, olehermanse commented
@cf-bottom please test this in jenkins, again.

2021-05-31 14:23 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=6650)](https://ci.cfengine.com//job/pr-pipeline/6650/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6650/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6650/

2021-05-31 17:14 UTC, olehermanse approved these changes

2021-05-31 17:14 UTC, merged