Added bootstrap/failsafe exclusion for directories named .no-distrib
cfengine/core pull request #4882
Opened 2021-12-08 20:44 UTC by nickanderson

With build.cfengine.com and cfbs released, we would like to be able to
distribute compliance reports as cfbs modules. We don't need (or necessarily
want) to distribute compliance report definitions to every host since they are
only useful for an enterprise hub, so we introduced this directory '.no-distrib'
as an excluded directory for bootstrap and failsafe.

With this change bootstrap/failsafe will exclude any directory named .no-distrib.
Note, until the update policy is updated with the same
exclusion, any policy update will receive the files in those directories.

Ticket: ENT-8079
Changelog: Title

2021-12-09 19:48 UTC, cf-bottom commented
Thank you for submitting a pull request! Maybe @olehermanse can review this?

2022-01-13 22:37 UTC, olehermanse requested changes

2022-01-13 22:37 UTC, olehermanse commented on libpromises/failsafe.cf
> +        depth_search => failsafe_u_infinate_client_policy,
```suggestion
        depth_search => failsafe_u_infinite_client_policy,
```

2022-01-13 22:37 UTC, olehermanse commented on libpromises/failsafe.cf
> +body depth_search failsafe_u_infinate_client_policy
```suggestion
body depth_search failsafe_u_infinite_client_policy
```

2022-01-14 15:13 UTC, nickanderson commented on libpromises/failsafe.cf
> +        depth_search => failsafe_u_infinate_client_policy,
ack

2022-01-14 15:13 UTC, nickanderson commented on libpromises/failsafe.cf
> +body depth_search failsafe_u_infinate_client_policy
ack

2022-01-14 16:06 UTC, merged