CFE-4093: Fixed VerifyInFstab() for MacOS
cfengine/core pull request #5090
Opened 2022-11-01 18:57 UTC by craigcomstock

TODO: check a few things, ensure there is a test

Ticket: CFE-4093
Changelog: title

2022-11-02 09:10 UTC, vpodzime submitted a review, later dismissed
ACK

2022-11-02 09:48 UTC, olehermanse requested changes
Please edit the changelog entry to show how this impacts a user. (VerifyInFstab() is an internal function users don't know about).

2022-11-08 22:30 UTC, olehermanse approved these changes

2022-11-08 22:30 UTC, merged

2022-11-15 15:12 UTC, craigcomstock commented
thanks @Lex-2008 for cherry picking to 3.15.x https://github.com/cfengine/core/pull/5106 and 3.18.x https://github.com/cfengine/core/pull/5105