CFE-4122: Fixed debug module expand logging for scalars
cfengine/core pull request #5142
Opened 2022-12-28 19:22 UTC by nickanderson

This naive change both removes un-necessary whitespace to align with the format
(namespace:bundle.varname) and fixes the output to include the variable name
instead of it's value.

Ticket: CFE-4122
Changelog: Title

2022-12-28 19:34 UTC, nickanderson commented
yeah, too naive i guess.

2022-12-28 20:39 UTC, larsewi approved these changes
ACK

2022-12-29 20:27 UTC, nickanderson commented
> ACK

are you sure about that ACK? the build failed didn't it?

2023-01-02 08:24 UTC, larsewi requested changes
Nope, `varstring` is a `char` (i.e. one character). The `%s` format specifier expects `char *`

2023-01-04 13:42 UTC, larsewi commented
With my changes the output looks like this:
```
$ sudo /var/cfengine/bin/cf-agent --log-modules=expand --debug | grep ExpandScalar | head
   debug: ExpandScalar((null):this.sys.local_libdir)  =>  lib
   debug: ExpandScalar((null):this.sys.local_libdir)  =>  lib
   debug: ExpandScalar((null):this.sys.domain)  =>  
   debug: ExpandScalar((null):this.def.domain)  =>  
   debug: ExpandScalar((null):this.sys.uqhost)  =>  hub
   debug: ExpandScalar((null):this.def.domain)  =>  
   debug: ExpandScalar((null):this.sys.policy_hub)  =>  192.168.56.10
   debug: ExpandScalar((null):(null).this.promiser)  =>  control_agent_abortclasses
   debug: ExpandScalar((null):(null).this.promiser)  =>  control_agent_abortbundleclasses
   debug: ExpandScalar((null):(null).sys.masterdir)  =>  /var/cfengine/masterfiles
```

2023-01-04 20:19 UTC, nickanderson commented
> With my changes the output looks like this:
> 
> ```
> $ sudo /var/cfengine/bin/cf-agent --log-modules=expand --debug | grep ExpandScalar | head
>    debug: ExpandScalar((null):this.sys.local_libdir)  =>  lib
>    debug: ExpandScalar((null):this.sys.local_libdir)  =>  lib
>    debug: ExpandScalar((null):this.sys.domain)  =>  
>    debug: ExpandScalar((null):this.def.domain)  =>  
>    debug: ExpandScalar((null):this.sys.uqhost)  =>  hub
>    debug: ExpandScalar((null):this.def.domain)  =>  
>    debug: ExpandScalar((null):this.sys.policy_hub)  =>  192.168.56.10
>    debug: ExpandScalar((null):(null).this.promiser)  =>  control_agent_abortclasses
>    debug: ExpandScalar((null):(null).this.promiser)  =>  control_agent_abortbundleclasses
>    debug: ExpandScalar((null):(null).sys.masterdir)  =>  /var/cfengine/masterfiles
> ```

I think this is more correct than it was, but some wonky stuff in there still for sure.

the `(null):` Is strange. I guess it's not in any specific namespace? Seems to me like it would be in the `default` namespace.

And others seem to have an extra `(null).`: e.g. `(null):(null).this.promiser` and `(null).sys.masterdir`

2023-01-04 20:20 UTC, nickanderson commented
Again, overall still an improvement, so I would tend to want to squash and merge this.

2023-01-09 10:10 UTC, larsewi commented
Now the log messages are less confusing:
```
   debug: Expanded scalar 'inputs' to 'inputs' using default namespace and this scope.
   debug: Expanded scalar '$(sys.local_libdir)/stdlib.cf' to 'lib/stdlib.cf' using current namespace and this scope.
   debug: Expanded scalar 'lib/stdlib.cf' to 'lib/stdlib.cf' using default namespace and cfengine_stdlib scope.
   debug: Expanded scalar 'inputs' to 'inputs' using default namespace and this scope.
   debug: Expanded scalar '$(sys.local_libdir)/stdlib.cf' to 'lib/stdlib.cf' using current namespace and this scope.
   debug: Expanded scalar 'lib/stdlib.cf' to 'lib/stdlib.cf' using default namespace and cfengine_stdlib scope.
   debug: Expanded scalar 'def_inputs' to 'def_inputs' using default namespace and this scope.
   debug: Expanded scalar 'controls/def.cf' to 'controls/def.cf' using current namespace and this scope.
   debug: Expanded scalar 'controls/def_inputs.cf' to 'controls/def_inputs.cf' using current namespace and this scope.
   ```

2023-01-30 10:55 UTC, larsewi approved these changes

2023-01-30 15:37 UTC, olehermanse approved these changes

2023-01-30 18:11 UTC, craigcomstock approved these changes
looks awesome!

2023-02-03 18:58 UTC, merged