ENT-9891: Symlink rpmvercmp only when needed
cfengine/core pull request #5209
Opened 2023-04-12 12:21 UTC by Lex-2008

Ticket: ENT-9891

Issue was that when "$RPMVERCMP" variable is not set, this command:

	ln "$RPMVERCMP" "$WORKDIR/bin"

was printing an unhelpful error message that it can't overwrite a
directory, thus polluting logs.

So the solution is to not run this command when this variable is not
set, a.k.a. when we don't need rpmvercmp.

2023-04-18 13:04 UTC, Lex-2008 commented
no noise build: https://github.com/cfengine/core/actions/runs/4732658642/jobs/8399189764

2023-04-19 13:48 UTC, craigcomstock requested changes
The commit comment doesn't make any sense to me.

What are you fixing, why is it a problem, how did you fix it?

2023-04-20 18:20 UTC, craigcomstock approved these changes

2023-04-21 18:24 UTC, merged

2023-04-25 10:21 UTC, Lex-2008 commented
cherry-picks: https://github.com/cfengine/core/pull/5226 and https://github.com/cfengine/core/pull/5227