Fix RlistEqual comparison on lists of different lengths
cfengine/core pull request #5313
Opened 2023-08-31 16:31 UTC by amousset

The original issue that leads to this is the fact that the caches for execresult and execresult_as_data were mixed ([CFE-4244](https://northerntech.atlassian.net/browse/CFE-4244)). This is caused by two separate issues:

* The function cache uses the args list as key and discards the function itself. This means different function with the same args are considered identical, and cache is reused.

https://github.com/cfengine/core/blob/57745c7afbd200a26b79a3a4dd79851781ff7ff1/libpromises/eval_context.c#L2840

* The function args are passed as an Rlist, and the used comparison ignores the additional items of the longest list when comparing two lists of different lengths, leading to treating execresult and execresult_as_data as identical when using the same command and shell args.

This PR only fixes the specific case of execresult, but leaves other function cache issues (e.g. host2ip vs. ip2host could be confused):

```cfengine
bundle agent main {
vars:
  "res1" string => host2ip("cfengine.com");
  "res2" string => ip2host("cfengine.com");
  "res3" string => ip2host("northerntech.atlassian.net");

reports:
  "res1: ${res1}";
  "res2: ${res2}";
}
```
still returns:

```
R: res1: 34.107.174.45
R: res2: 34.107.174.45
R: res3: northerntech.atlassian.net
```

_Note_: Even if the function names suggests lists of different lengths should be different, we might break other stuff using Rlists, I haven't tried to investigate other use cases.

2023-09-01 11:24 UTC, larsewi requested changes
Very nice 🚀 I have only a few nitpicks.

Thank you for providing both an acceptance- and unit tests. I see that your acceptance test fails on Windows, and I'm not quite sure why. I will request a build from @cf-bottom in Jenkins, so that I can investigate this further. Feel free to address the suggested changes in the meanwhile.

2023-09-01 11:24 UTC, larsewi commented on libpromises/rlist.c
> +    }
Could be written as a single statement
```suggestion
    // return false if lengths are different
    return (rp1 == NULL && rp2 == NULL);
```

2023-09-01 11:24 UTC, larsewi commented on tests/unit/rlist_test.c
> +
```suggestion

```

2023-09-01 15:59 UTC, amousset commented
>  I see that your acceptance test fails on Windows, and I'm not quite sure why.

I you think it would be acceptable I could skip this test on Windows and macOS.

2023-09-07 12:22 UTC, larsewi commented
Hi @amousset, I just tested this manually on Windows, and you can fix it my using `"powershell"` instead of `"useshell"` as the second argument of `execresult()` and `execresult_as_data()` on Windows. You can achieve this by for example using the `windows::` classguard.

2023-09-07 12:43 UTC, amousset commented on tests/acceptance/01_vars/04_containers/execresult_and_as_data.cf
> +     "res2" data   => execresult_as_data("echo test", "powershell", "stdout");
indeed :facepalm:

2023-09-07 12:52 UTC, larsewi commented
Awesome, thanks 🚀  Let's run this though CI again, just to make sure everything is good [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=9743)](https://ci.cfengine.com/job/pr-pipeline/9743/)

2023-09-07 13:40 UTC, amousset commented
Second part addressed in https://github.com/cfengine/core/pull/5317

2023-09-08 09:17 UTC, larsewi commented
Could you please squash the commits as described in https://github.com/cfengine/core/blob/master/CONTRIBUTING.md#interactive-rebase?

2023-09-11 12:14 UTC, larsewi commented on tests/acceptance/01_vars/04_containers/execresult_and_as_data.cf
> +     "res2" data   => execresult_as_data("echo test", "powershell", "stdout");
Looks like the change disappeared after your force push
```suggestion
    !windows::
     "res1" string => execresult("echo test", "useshell");
     "res2" data   => execresult_as_data("echo test", "useshell", "stdout");
    windows::
     "res1" string => execresult("echo test", "powersell");
     "res2" data   => execresult_as_data("echo test", "powershell", "stdout");
```

2023-09-12 11:14 UTC, larsewi commented
Still failing on Windows 🤔  I will create a new build, investigate further, and then get back to you. [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=9798)](https://ci.cfengine.com/job/pr-pipeline/9798/)

2023-09-12 11:16 UTC, larsewi commented on tests/acceptance/01_vars/04_containers/execresult_and_as_data.cf
> +     "res1" string => execresult("echo test", "powersell");
I think I found it. Little typo
```suggestion
     "res1" string => execresult("echo test", "powershell");
```

2023-09-12 12:47 UTC, larsewi commented
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=9800)](https://ci.cfengine.com/job/pr-pipeline/9800/) 🤞

2023-09-13 09:27 UTC, larsewi approved these changes
Thanks for your contribution 🚀

2023-09-13 09:27 UTC, merged

2023-09-13 09:29 UTC, larsewi commented
Seems that the GitHub Action workflow for windows acceptance tests, tests with master nightly build, instead of testing it with the changes you did to core. Thus I merged this, and will see if it passes when we have a new master nightly build.