Added changelog for 3.18.6
cfengine/core pull request #5328
Opened 2023-09-18 17:02 UTC by larsewi

2023-09-18 18:36 UTC, nickanderson requested changes
I see a misspelling and a missing entry for ENT-10336

2023-09-18 18:36 UTC, nickanderson commented on ChangeLog
> +	- Cashed policy function results now take into account number of arguments
```suggestion
	- Cached policy function results now take into account number of arguments
```

2023-09-18 18:36 UTC, nickanderson commented on ChangeLog
> +
```suggestion
	- Fixed misleading error message when adding CMDB classes (ENT-10336)
	- 
```

2023-09-18 20:31 UTC, olehermanse commented on ChangeLog
> +	- package[update]smatching now looks for the software inventory databases
```suggestion
	- packagesmatching() and packageupdatesmatching() now look for the software inventory databases
```

2023-09-18 20:33 UTC, olehermanse commented on ChangeLog
> +	  in the state directory and uses them if found. This change enables the
```suggestion
	- packagesmatching() and packageupdatesmatching() now look for the software
	  inventory databases in the state directory and use them if found. This change enables the
```

2023-09-18 21:08 UTC, olehermanse approved these changes

2023-09-19 11:08 UTC, larsewi commented
Squashed commits

2023-09-19 14:27 UTC, olehermanse approved these changes

2023-09-19 14:38 UTC, nickanderson approved these changes

2023-09-26 22:14 UTC, merged