Modify all calls to `WriterWriteHelp` to adapt to API change
cfengine/core pull request #5339
Opened 2023-10-06 08:41 UTC by lluiscampos

2023-10-06 08:41 UTC, lluiscampos commented
Depends on:
* https://github.com/cfengine/libntech/pull/194

2023-10-06 09:49 UTC, vpodzime reviewed
Looks good to me otherwise. It will need changes in other CFEngine repos, but I can take care of that. Thanks!

2023-10-06 09:49 UTC, vpodzime commented on cf-agent/cf-agent.c
> +    .copyright = "2023 Northern.tech AS"
Website and copyright should be macros defined in either `cf3.defs.h` or in `config.h` (by means of autotools). We don't want to update them in multiple places.

2023-10-06 12:13 UTC, vpodzime commented
@cf-bottom jenkins, please

2023-10-06 12:33 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=9937)](https://ci.cfengine.com//job/pr-pipeline/9937/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9937/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9937/

2023-10-06 14:43 UTC, olehermanse requested changes
Great work, but looks like this needs at least a change in enterprise repo for windows to compile.

2023-10-09 08:43 UTC, vpodzime commented
> Great work, but looks like this needs at least a change in enterprise repo for windows to compile.

What do you mean @olehermanse? I see this:
>  ci/testing_pr/PACKAGES_i386_mingw — Build and tests finished: success 
>  ci/testing_pr/PACKAGES_x86_64_mingw — Build and tests finished: success

2023-10-11 10:02 UTC, larsewi commented
Tested, built together with https://github.com/cfengine/nova/pull/2130#issuecomment-1754585718. And it seems to work :)

2023-10-11 10:03 UTC, larsewi approved these changes

2023-10-11 10:03 UTC, larsewi commented
> Merging can be performed automatically once the requested changes are addressed.

Not able to merge

2023-10-11 11:56 UTC, olehermanse approved these changes

2023-10-11 11:56 UTC, merged

2023-10-12 18:26 UTC, craigcomstock commented
@lluiscampos @olehermanse did we really want to remove all the Commands: text from the help?

It used to be
```
$ /var/cfengine/bin/cf-check --help

cf-check:
        Utility for diagnosis and repair of local CFEngine databases.
        This BETA version of the tool is for testing purposes only.

Commands:
        dump - Print the contents of a database file
        diagnose - Assess the health of one or more database files
        backup - Copy database files to a timestamped folder
        repair - Diagnose, then backup and delete any corrupt databases
        version - Print version information
        help - Print this help menu

Usage:
        $ cf-check <command> [options] [file ...]

Examples:
        $ cf-check dump /var/cfengine/state/cf_lastseen.lmdb
        $ cf-check lmdump -a /var/cfengine/state/cf_lastseen.lmdb
        $ cf-check diagnose
        $ cf-check repair
```

But now is
```
$ cf-check --help
Usage: cf-check [OPTIONS] [FILE]

Options:
  --help        , -h value - Print the help message
  --manpage     , -M       - Print the man page
  --version     , -V       - Output the version of the software
  --debug       , -d       - Enable debugging output
  --verbose     , -v       - Enable verbose output
  --log-level   , -g value - Specify how detailed logs should be. Possible values: 'error', 'warning', 'notice', 'info', 'verbose', 'debug'
  --inform      , -I       - Enable basic information output

Website: https://cfengine.com
This software is Copyright 2023 Northern.tech AS.
```

Not quite as informative as it should be I think.

2023-10-13 06:32 UTC, lluiscampos commented
> @lluiscampos @olehermanse did we really want to remove all the Commands: text from the help?
> 

Thanks for reporting.

The commands were indeed removed by mistake. See the follow-up in #5353. See discussion there for what happened to the examples.