CFE-3991: Added version_compare() policy function
cfengine/core pull request #5349
Opened 2023-10-10 17:10 UTC by olehermanse

This function can be used to compare 2 arbitrary semver version
numbers. This can be useful if you have 2 versions of a package
and you want to know if they are the same version, if one is
newer than the other etc.

Internally, it uses the same version comparison logic as
the cf_version functions (cf_version_minimum, etc.). This means
that only the major.minor.patch parts of the version string
are compared, the rest is discarded, so
3.2.1 = 3.2.1-1 = 3.2.1-2 etc.

Depends on:
https://github.com/NorthernTechHQ/libntech/pull/196

2023-10-10 17:13 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=9940)](https://ci.cfengine.com//job/pr-pipeline/9940/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9940/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9940/

2023-10-10 17:19 UTC, olehermanse commented
Currently failing because this one has not been merged yet: https://github.com/cfengine/core/pull/5339

2023-10-10 17:34 UTC, nickanderson approved these changes
Good, suggested expansion of example to show part of string that is discarded. But still ok without that.

2023-10-11 08:15 UTC, vpodzime reviewed
Looks good to me otherwise.

2023-10-11 08:15 UTC, vpodzime commented on libpromises/evalfunction.c
> +            "Cannot comapre versions: %s(\"%s\", \"%s\", \"%s\")",
*comapre!*

2023-10-11 08:15 UTC, vpodzime commented on libpromises/evalfunction.c
> +    {CF_ANYSTRING, CF_DATA_TYPE_STRING, "Operator to use in comparison (=, !=, <, >, <=, >=)"},
Shouldn't this use a regex for the allowed strings?

2023-10-11 13:46 UTC, craigcomstock requested changes
a few typos I think

2023-10-11 13:46 UTC, craigcomstock commented on libpromises/evalfunction.c
> +            "Policy fuction %s requires 3 arguments:"
```suggestion
            "Policy function %s requires 3 arguments:"
```

:O

2023-10-11 13:46 UTC, craigcomstock commented on libpromises/evalfunction.c
> +    FnCallTypeNew("cf_version_minimum", CF_DATA_TYPE_CONTEXT, VERSION_COMPARE_ARGS, &FnCallVersionCompare, "Compare two version numbers with a specified operator (=, !=, <, >, <=, >=)",
```suggestion
    FnCallTypeNew("version_compare", CF_DATA_TYPE_CONTEXT, VERSION_COMPARE_ARGS, &FnCallVersionCompare, "Compare two version numbers with a specified operator (=, !=, <, >, <=, >=)",
```

2023-10-11 14:08 UTC, olehermanse commented on libpromises/evalfunction.c
> +    FnCallTypeNew("cf_version_minimum", CF_DATA_TYPE_CONTEXT, VERSION_COMPARE_ARGS, &FnCallVersionCompare, "Compare two version numbers with a specified operator (=, !=, <, >, <=, >=)",
Thanks!

2023-10-11 14:08 UTC, olehermanse commented on libpromises/evalfunction.c
> +            "Policy fuction %s requires 3 arguments:"
Thanks!

2023-10-11 14:09 UTC, olehermanse commented on libpromises/evalfunction.c
> +            "Cannot comapre versions: %s(\"%s\", \"%s\", \"%s\")",
Nice one, fixed :)

2023-10-11 14:10 UTC, olehermanse commented on examples/version_compare.cf
> +      if => version_compare("3.24.1", ">=", "3.24.1");
I disagree, I want the examples to be very simple. This can be covered by docs and tests.

2023-10-11 14:15 UTC, olehermanse commented
@cf-bottom jenkins, please :)

2023-10-11 14:18 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=9943)](https://ci.cfengine.com//job/pr-pipeline/9943/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9943/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9943/

2023-10-11 14:41 UTC, nickanderson commented on libpromises/evalfunction.c
> +    FnCallTypeNew("version_compare", CF_DATA_TYPE_CONTEXT, VERSION_COMPARE_ARGS, &FnCallVersionCompare, "Compare two version numbers with a specified operator (=, !=, <, >, <=, >=)",
I see that you have `=` here, but not `==` which is used in one of the tests.

2023-10-11 15:58 UTC, olehermanse commented
@cf-bottom jenkins, please

2023-10-11 16:37 UTC, nickanderson submitted a review, later dismissed

2023-10-11 16:37 UTC, craigcomstock submitted a review, later dismissed
cool, wait for jenkins then yeah? 👍

2023-10-11 17:37 UTC, olehermanse commented
@cf-bottom jenkins, please

2023-10-11 17:38 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=9945)](https://ci.cfengine.com//job/pr-pipeline/9945/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9945/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9945/

2023-10-11 17:44 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=9946)](https://ci.cfengine.com//job/pr-pipeline/9946/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9946/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9946/

2023-10-11 18:13 UTC, cf-bottom commented
Sure, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=9947)](https://ci.cfengine.com//job/pr-pipeline/9947/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9947/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9947/

2023-10-11 19:02 UTC, larsewi approved these changes
Nice 🚀

2023-10-11 20:06 UTC, craigcomstock approved these changes

2023-10-11 20:24 UTC, merged