Added sys.os_name_human for Alpine and PostmarketOS
cfengine/core pull request #5464
Opened 2024-03-01 01:32 UTC by craigcomstock

PostmarketOS is after Alpine since it is derived from Alpine

Ticket: none
Changelog: none

2024-03-01 01:34 UTC, craigcomstock commented
on PostmarketOS, /etc/os-release contains:

PRETTY_NAME="postmarketOS v23.12"
NAME="postmarketOS"
VERSION_ID="v23.12"
VERSION="v23.12"
ID="postmarketos"
ID_LIKE="alpine"
HOME_URL="https://www.postmarketos.org/"
SUPPORT_URL="https://gitlab.com/postmarketOS"
BUG_REPORT_URL="https://gitlab.com/postmarketOS/pmaports/issues"
LOGO="postmarketos-logo"

2024-03-01 01:35 UTC, craigcomstock commented
As seen in /etc/os-release, postmarketOS is capitalized with a lowerase p at the beginning

2024-03-01 09:16 UTC, larsewi submitted a review, later dismissed

2024-03-01 12:56 UTC, craigcomstock commented
Oops, got the order wrong and missed the derived-from. While I'm at it, might as well add some more BSD that I can test.

2024-03-01 13:09 UTC, olehermanse requested changes
`derived-from` is used to indicate which class caused you to set this value.

2024-03-01 13:09 UTC, olehermanse commented on libenv/sysinfo.c
> +                                      "source=agent,derived-from=netbsd");
```suggestion
                                      "source=agent,derived-from=openbsd");
```

2024-03-01 13:09 UTC, olehermanse commented on libenv/sysinfo.c
> +                                      "source=agent");
```suggestion
                                      "source=agent,derived-from=netbsd");
```

2024-03-01 13:09 UTC, olehermanse commented on libenv/sysinfo.c
> +                                      "source=agent,derived-from=alpine");
```suggestion
                                      "source=agent,derived-from=postmarketos");
```

2024-03-01 13:09 UTC, olehermanse commented on libenv/sysinfo.c
> +                                      "source=agent");
```suggestion
                                      "source=agent,derived-from=alpine");
```

2024-03-01 15:24 UTC, craigcomstock commented
> `derived-from` is used to indicate which class caused you to set this value.

makes sense. for some reason I saw it differently and was thinking about lineage and derivation like ubuntu derived-from debian ;) Thanks. :)

2024-03-01 17:21 UTC, olehermanse approved these changes

2024-03-01 17:21 UTC, olehermanse commented
@cf-bottom jenkins, please

2024-03-01 17:23 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=10519)](https://ci.cfengine.com//job/pr-pipeline/10519/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10519/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10519/

2024-03-05 21:19 UTC, larsewi approved these changes

2024-03-19 15:36 UTC, olehermanse requested changes
Please update commit with:

```
Changelog: Title
```

Some open source users of these OSes might find this useful.

2024-03-20 08:21 UTC, larsewi approved these changes

2024-03-21 14:47 UTC, olehermanse approved these changes

2024-03-21 14:49 UTC, merged