masterfiles-stage.sh --check-only
cfengine/core pull request #5524
Opened 2024-06-03 10:45 UTC by vpodzime

2024-06-03 11:44 UTC, larsewi submitted a review, later dismissed
🚀

2024-06-03 14:48 UTC, nickanderson approved these changes

2024-06-03 15:04 UTC, craigcomstock reviewed
shellcheck would probably say

```
if [ "x$1" = "xtrue" ]; then
     ^---^ SC2268 (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
```

So maybe change that to be tidy.

2024-06-03 15:14 UTC, vpodzime commented
> it no longer serves a purpose

How come? I'm not checking `$#` so doing `x$1` is the only way to avoid an empty string there in cases no argument is passed.

2024-06-04 14:54 UTC, craigcomstock commented
> How come? I'm not checking $# so doing x$1 is the only way to avoid an empty string there in cases no argument is passed.

`test` aka `[` on all the shells we will use will almost certainly not have this problem of empty string as it did in days past.

https://www.shellcheck.net/wiki/SC2268

What you wrote doesn't hurt, I just like using shellcheck and think it gives generally excellent advice.

2024-06-05 13:51 UTC, vpodzime commented
> all the shells we will use will almost certainly not have this problem

Sounds amazing! :grin:

2024-06-05 15:39 UTC, craigcomstock submitted a review, later dismissed

2024-06-05 17:45 UTC, mikeweilgart requested changes
From a code design standpoint this is a major change; I think passing the check_only flag to every single function as an argument is a mistake.  A global variable would be more in keeping, much like the way debug logging is currently handled.  But even better would be to add the necessary new functions and keep them simple.

Overall this seems to make the code more complicated and harder to understand as it adds a second and mutually exclusive path through almost every function, and a separate return point or two.  (Effectively, a whole bunch of "gotos" have been added.)

@tdlee may be interested to review this as well since his use of this code is more regular than mine.

2024-06-05 21:29 UTC, vpodzime commented on contrib/masterfiles-stage/common.sh
> +  work_tree_rev="$(cat "$2/.git/HEAD")"
yup, it's used by `cf-promises -T` so it gets copied over.

2024-06-06 09:03 UTC, vpodzime commented
> From a code design standpoint this is a major change; I think passing the check_only flag to every single function as an argument is a mistake. A global variable would be more in keeping, much like the way debug logging is currently handled. But even better would be to add the necessary new functions and keep them simple.

I'd argue that using global variables is a mistake. :wink: :slightly_smiling_face: But since they are already used extensively, adding one more would not be a problem. @nickanderson @olehermanse opinions?

Regarding new simple functions -- yes, that would be nice for sure, but since the logic of what is being checked out and where is buried deep in the functions we have, I'd have to reimplement the same logic. That's why it made more sense to me to keep the logic in one place and then just do a different thing when only checking for updates.

2024-06-06 09:04 UTC, vpodzime commented
> @tdlee may be interested to review this as well since his use of this code is more regular than mine.

yup! The more :eyes: the better!

2024-06-06 09:38 UTC, vpodzime commented on contrib/masterfiles-stage/common.sh
> +  mirror_rev="$(git --git-dir="$1" show --pretty=format:%H -s "$3" | tail -n1)"
`^0` works nicely. Thanks!

2024-06-06 13:45 UTC, olehermanse commented
> > How come? I'm not checking $# so doing x$1 is the only way to avoid an empty string there in cases no argument is passed.
> 
> `test` aka `[` on all the shells we will use will almost certainly not have this problem of empty string as it did in days past.
> 
> https://www.shellcheck.net/wiki/SC2268
> 
> What you wrote doesn't hurt, I just like using shellcheck and think it gives generally excellent advice.

@craigcomstock @vpodzime FYI, I followed that link, and then the link to a related resource, which says;

> I was unfortunately unable to peer into the closely guarded world of the likes of HP-UX and AIX, so dinosaur herders beware.

https://www.vidarholen.net/contents/blog/?p=1035

So....

2024-06-06 18:18 UTC, nickanderson commented
> I'd argue that using global variables is a mistake. 😉 🙂 But since they are already used extensively, adding one more would not be a problem. @nickanderson @olehermanse opinions?

I have no strong opinion here.  Your change while perhaps not ideal is still small. We already have other duplication. I would say a great refactor would be a separate issue.

2024-06-07 12:51 UTC, craigcomstock approved these changes

2024-06-13 16:01 UTC, olehermanse approved these changes

2024-06-17 08:03 UTC, larsewi approved these changes

2024-06-18 09:05 UTC, merged